### ISSUE TITLE
How to send deep link without inApp.

### ISSUE THREAD

**Issue by daspuru** [mattosaurus/UrbanAirshipCore#1]
Hello!

Thanks for your great software. I am trying to send a push notification with a deep link, but I see the only apparent way to do such thing with this framework is to put it inside the inApp message, however the UA API let´s put the Actions object in the main node of the JSON request. Is there any method to do such thing?

Thanks..

**Comment by daspuru** [comment]
Ok, I found a solution. 

I added the following property to the Notification object:

`/// <summary>
        /// An Actions object specifying actions which occur when the user taps on the banner notification.
        /// </summary>
        [JsonProperty("actions")]
        public Action.Action Actions { get; set; }`

And then just added the deep link information to the Notification this way:

`notification.Actions = new UrbanAirshipCore.Models.Action.Action();
                    notification.Actions.OpenAction = new OpenAction();
                    notification.Actions.OpenAction.Type = "deep_link";
                    notification.Actions.OpenAction.Content = "bundle.identifier://url-data";
                    notification.Actions.OpenAction.FallbackUrl = "bundle.identifier://url-data";`

That works :)

**Comment by mattosaurus** [comment]
Good spot!

Looks like I missed that notifications have actions. I've updated the code and have published a new version (1.2.1) of the package to NuGet. Let me know if you spot anything else, this is still very much a work in progress.
